# Generated by Django 4.2 on 2025-04-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_address_default_address'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=750)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('comment_date', django_jalali.db.models.jDateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('لغو', 'failed'), ('درحال پردازش', 'pending!'), ('ارسال شده', 'completed')], default='درحال پردازش', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactiondate',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='store.product'),
        ),
    ]
