# Generated by Django 4.2 on 2025-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_comment_remove_product_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('درحال پردازش', 'pending!'), ('ارسال شده', 'completed'), ('لغو', 'failed')], default='درحال پردازش', max_length=20),
        ),
    ]
